name: Influx test on Linux
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Install sitespeed.io
      run: |
        git clone https://github.com/sitespeedio/sitespeed.io.git
        cd sitespeed.io
        npm install
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Install dependencies
      run: |
          python -m pip install --upgrade --user pip
          python -m pip install --user scipy
          python -m pip show scipy
    - name: Setup environment
      run: docker compose -f test/docker/docker-compose.yml up -d
    - name: Browser versions
      run: |
        google-chrome --version
    - name: Info
      run: |
        ls -la
    - name: Run test with Influx 1.8
      run: cd sitespeed.io && bin/sitespeed.js https://www.sitespeed.io -n 1 --influxdb.host 127.0.0.1 --xvfb --resultBaseUrl https://result.sitespeed.io --influxdb.annotationScreenshot=true --plugins.add ../../../lib/index.js
    - name: Run test with Influx 2.6.1
      run: sitespeed.io https://www.sitespeed.io -n 1 --influxdb.host 127.0.0.1 --influxdb.port 8087 --influxdb.version 2 --influxdb.organisation sitespeed --influxdb.token sitespeed --xvfb --resultBaseUrl https://result.sitespeed.io --influxdb.annotationScreenshot=true --plugins.add ./lib/index.js